//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxuryHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public string Titile { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string img { get; set; }
        public Nullable<System.DateTime> Date_Of_Create { get; set; }
        public string Author { get; set; }
    }
}
